### ISSUE TITLE
Интеграция видео в свайпер

### ISSUE THREAD

**Issue by maestto** [OnePageWizard/TheaterPeople#4]
Видео уже приходит с CMS и размещается на странице, осталось реализовать логику, разместив видео после изображений в слайдере.

> ![image](https://github.com/OnePageWizard/TheaterPeople/assets/50048111/f1af63fe-1e90-4841-b64d-d8352d858d26)
Текущий вид раздела подростков на странице обучения

**Comment by oriboni** [comment]
Мы же вроде говорили, что видос отдельно. Так будет намного понятнее пользователю

**Comment by maestto** [comment]
> Мы же вроде говорили, что видос отдельно. Так будет намного понятнее пользователю

Пока что это не является обязательным, поэтому я использую метку `enhancement`. Я уточню у Наташи этот вопрос, когда буду показывать ей то, что готово.

**Comment by maestto** [comment]
Узнал у Наташи. Видео в свайпере на странице обучение не нужно, будет отдельно.
